### PR TITLE
Editorial: Change the name of 'options' to 'properties' when not optional

### PR DESCRIPTION
**Pull request by ptomato**
See discussion in #1720.

### CODE REVIEW

**Comment by ljharb** [comment]
I don't think the name of the argument is relevant - an object full of stuff is an options bag regardless of its name, and required things belong as positional arguments.

**Comment by ljharb** [comment]
("properties" to me kinds of sounds like `['a', 'b']` - ie, an array of property names)

**Comment by ptomato** [comment]
I agree, but I don't have an idea for a better name, do you have a suggestion?

(I do think that `options` is not the best name, so I think this should be changed regardless of the outcome of #1756. But I'm also happy to close this and roll it into whatever becomes the eventual solution of that issue.)

**Comment by ptomato** [comment]
Superseded by #1875. I suggested there to change the terminology to "configuration object" which was suggested by Yulia during the plenary.

**Pull request closed without merging**
