### PR TITLE
built-in module -> global object

### PR DESCRIPTION
**Pull request by hax**
GitHub also auto change the encoding from UTF-16LE to UTF-8.

### CODE REVIEW

**Comment by hax** [comment]
@ljharb  See my original comment. 

And u could use rich diff to see the changes.

**Comment by ljharb** [comment]
utf-8 isn’t a binary file, and the diffs would show.

**Comment by ljharb** [comment]
I do see that on the desktop site, they show up, but not the mobile site.

**Comment by ljharb** [comment]
Can that be reverted? It shouldn’t be necessary to make a markdown file “binary” on github to make prose changes.

**Comment by Ms2ger** [comment]
Please rebase on main; I fixed the encoding there.

**Comment by hax** [comment]
it seems no way to rebase in github... i just close this and will create new pr.

**Pull request closed without merging**
