### PR TITLE
Date/Time.toZonedDateTime

### PR DESCRIPTION
**Pull request by Ms2ger**
See #889.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Docs will need an update too.

**Review by justingrant — APPROVED** [review]
Looks great!

**Review by ptomato — APPROVED** [review]
I rebased these and it was straightforward. :+1:

**Comment by ptomato** [comment]
Let's keep the docs change for a follow-up.

**Comment by justingrant** [comment]
I'm already planning to do the TS types updates corresponding to this and similar PRs, so I can do the docs updates too as part of that.

**Pull request merged**
