### PR TITLE
Correct minor problem with script examples which results in an error when run

### PR DESCRIPTION
**Pull request by cwadrupldijjit**
modified "const" to "let" since the code sample would fail in the reassignment on the next line

### CODE REVIEW

**Comment by cwadrupldijjit** [comment]
Wait, how in the world does changing a .md file (technically decreasing the size, too) actually decrease the code coverage?  That doesn't make any sense!  There _has_ to be more to that...

**Comment by cwadrupldijjit** [comment]
Okay, never mind.  It just updated to saying the code coverage won't change...

**Comment by ryzokuken** [comment]
> Wait, how in the world does changing a .md file (technically decreasing the size, too) actually decrease the code coverage? That doesn't make any sense! There has to be more to that...

Sorry about that, `codecov` takes a while to calculate and updates asynchronously.

**Comment by justingrant** [comment]
Does [coveralls](https://coveralls.io/) work better? I admit that `codecov`'s spam was confusing to me too.

**Comment by ptomato** [comment]
It should work fine again when we have fully ported the demitasse tests over to test262. The problem is that codecov gets confused about the two test suites when one finishes earlier than the other. I haven't investigated if coveralls does handle this.

**Comment by ryzokuken** [comment]
I think it's a better idea to put more effort into porting the tests than spend time trying to find an alternative to codecov, to be honest.

**Comment by justingrant** [comment]
Sounds reasonable. re: porting the tests, once very useful thing about the demitasse tests is that they all run in <5s, but the Test262 tests take 5+ minutes to run. This makes iterative testing really challenging. Is there a way to speed them up?

**Comment by ryzokuken** [comment]
The test262 harness isn't the fastest or the most feature-rich, but any additions/improvements would directly help all other tc39 efforts, so it seems worth looking into.

**Comment by justingrant** [comment]
Agreed.  My main suggestion would be to wait a few months to port our existing tests until the rate of change slows down, because having tests run 50x-100x slower would make it much more time-consuming to make changes to Temporal.

**Comment by ptomato** [comment]
I agree, that was my intention as well. (FWIW, when I was investigating this, I found the test262 harness isn't inherently slow. The slowdown comes from eval'ing the entirety of the bundled Temporal polyfill that gets prepended to every test because there isn't a better way to install Temporal into the test262 environment. That's why, when I reduced the size of the bundle, the test262 ran faster by several minutes.)

**Pull request merged**
