### PR TITLE
monthsInYear and daysInWeek

### PR DESCRIPTION
**Pull request by ptomato**
Closes: #634

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]
Thanks

**Review by ryzokuken — APPROVED** [review]
Thanks

**Comment by ryzokuken** [comment]
@ptomato lint error, can you take a look?

**Review by sffc — APPROVED** [review]
Assuming you have a plan to resolve the `<mark>TODO: Make calendar-aware along with all the other properties.</mark>`?

**Comment by ptomato** [comment]
Thanks, both, for the reviews!

> @ptomato lint error, can you take a look?

Oops, fixed.

> Assuming you have a plan to resolve the `<mark>TODO: Make calendar-aware along with all the other properties.</mark>`?

Indeed, one of Ms2ger or Ujjwal or I will do that, we can't request Stage 3 review without it...

**Pull request merged**
