### PR TITLE
Add a note about precision to SystemInstant.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please bikeshed the wording

**Comment by ptomato** [comment]
I don't see anything wrong with this wording, maybe we should just go for it and see if the editors would like to word it differently during the review stage?

**Comment by ryzokuken** [comment]
Adding to agenda, will merge after the tiniest bit of bikeshedding.

**Review by ryzokuken — APPROVED** [review]

**Comment by ptomato** [comment]
This wording seemed OK in today's meeting, merging.

**Pull request merged**
