### PR TITLE
polyfill: fix the Instant methods types

### PR DESCRIPTION
**Pull request by artalar**
Based on https://github.com/tc39/proposal-temporal/blob/732751277ed13c65f82fb55496354c428ebc58b3/polyfill/lib/instant.mjs#L63

### CODE REVIEW

**Comment by artalar** [comment]
Sorry, I need to test it first

**Comment by artalar** [comment]
I rechecked a few cases, looks ok.

**Review by ryzokuken — APPROVED** [review]
This is great stuff, @artalar! Thanks a ton!

For TS noobs like me, https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys should help,

**Comment by justingrant** [comment]
Sorry, I'm very late in reviewing this! @artalar, I have a few questions: 

1) Does this PR cause new compiler errors compared to the previous .d.ts content?  For example, will either of the lines below cause a TS error with this PR?  (They'll both cause runtime errors.)
```ts
Temporal.now.instant().add(Temporal.Duration.from('P10DT2H'));
Temporal.now.instant().add({ days: 10, hours: 2 });
```
2) If the answer to (1) is "no" then is the main benefit of this PR that it will limit autocomplete to valid properties?  That's a good justification for this PR, but I'm just wondering if there are other benefits besides that one. 
3) What's the benefit of wrapping the `Omit` around the Duration type (the class type), as opposed to only wrapping `DurationLike` (the object literal type)?  I don't think `Omit`-ing the class type hurts anything, but I was wondering if it helps anything.

**Comment by ryzokuken** [comment]
I think it will infact throw a compile error in the second example, not sure about the first but I guess @artalar could confirm.

**Pull request merged**
