### PR TITLE
Use US spelling in docs (behaviour => behavior)

### PR DESCRIPTION
**Pull request by ptomato**
I split this out of #1875 so that this part is not blocked on anything.

### CODE REVIEW

**Comment by ptomato** [comment]
@justingrant Mind giving this a rubber stamp? I'll take care of rebasing your PR once this lands

**Review by justingrant — APPROVED** [review]
@ptomato, as my neighbour to the North, you are taking this change with quite good humour. I aplogise that we have to do this, and I recognise that it must be annoying to spend so much labour on what must seem like a false pretence.  If only we could catalyse some changes. Anyway, I'm grateful that you don't take offence to this manoeuvre.  

And I thought you might enjoy what en-US Chrome thinks of this comment. 😄

image

**Comment by ptomato** [comment]
citizen_kane_clap.gif

**Comment by gibson042** [comment]
Sorry to rain on the parade, but ECMA-262 actually uses OED spelling—cf. https://github.com/tc39/ecma262/issues/1649 and https://github.com/tc39/ecma262/pull/1856 .

**Comment by ljharb** [comment]
That’s in the spec; this is the docs.

**Pull request merged**
