### PR TITLE
Add a badge for specifying current stage

### PR DESCRIPTION
**Pull request by aleen42**
According to https://es.discourse.group/t/a-standard-badge-for-tc39/731, automatically generate a badge for specifying current stage of the proposal.

### CODE REVIEW

**Comment by ljharb** [comment]
I think such a badge would have to be hosted by tc39.

**Comment by ryzokuken** [comment]
Right, a badge hosted at someone's personal website could potentially become a security issue, I feel.

**Comment by ljharb** [comment]
It also wouldn’t meet ecma’s archival requirements.

**Comment by aleen42** [comment]
@ljharb sorry for the confusing spam.

**Comment by ljharb** [comment]
@aleen42 the idea is interesting, and I’d like to see it explored further, it’s just premature to add it to a proposal prior to working out details.

**Comment by aleen42** [comment]
@ljharb 👌🏼

**Pull request closed without merging**
