### PR TITLE
 replaced  ÷ with /

### PR DESCRIPTION
**Pull request by aaryanporwal**
Replaced all ÷ operator with / , closing issue #953

### CODE REVIEW

**Comment by ryzokuken** [comment]
You removed spaces before the operator too, please add them back.

**Comment by aaryanporwal** [comment]
On it !

**Comment by aaryanporwal** [comment]
Added the spaces back! @ryzokuken

**Review by ryzokuken — APPROVED** [review]
Thanks.

**Comment by ljharb** [comment]
See also, #956.

**Comment by ryzokuken** [comment]
Closed in favor of #956

**Pull request closed without merging**
