### PR TITLE
Normative: Use internal slot in UnbalanceDurationRelative.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by ptomato — APPROVED** [review]
Oops, this looks like my mistake, and I agree it's a normative change

**Comment by ptomato** [comment]
I've added Frank's additional fixes from #1673 here, to consolidate the two pull requests, and added test coverage for each entry point where this happens.

**Comment by FrankYFTang** [comment]
thanks

**Comment by ptomato** [comment]
This change achieved consensus in TC39.

**Pull request merged**
