### PR TITLE
Move tests for PlainDate#{toString,equals}.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by ptomato — APPROVED** [review]
More tests moving upstream, great!

**Comment by ptomato** [comment]
It looks like updating test262 broke `built-ins/Temporal/PlainDate/from/argument-object.js`:

```
FAIL built-ins/Temporal/PlainDate/from/argument-object.js (strict mode)

evalmachine.<anonymous>:1550
  throw new Test262Error(message);
  ^

Test262Error {
  message: '31 era result Expected SameValue(«undefined», «bad fields with missing overflow») to be true'
}
```
(also I think the submodule commit needs to be updated to match the commit hash that actually made it onto the test262 main branch, because I think the test262 PR was rebased when it was merged)

**Comment by Ms2ger** [comment]
Probably https://github.com/tc39/test262/pull/3368 - will look later this week

**Comment by ptomato** [comment]
No worries, I just updated to a newer commit and everything works now.

**Pull request merged**
